/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "inverse-primary": "#E9D5FF",
        "on-primary": "#FFFFFF",
        "tertiary-fixed-dim": "#A0A5C2",
        "on-primary-fixed-variant": "#2D1575",
        "primary": "#5F2EFF",
        "on-tertiary-fixed": "#FFFFFF",
        "inverse-on-surface": "#FFFFFF",
        "background": "#080D21",
        "surface-container-low": "#0C112C",
        "on-secondary-fixed-variant": "#7C3AED",
        "surface-tint": "#5F2EFF",
        "surface-dim": "#080D21",
        "secondary-fixed": "#1E1B4B",
        "inverse-surface": "#050816",
        "primary-fixed-dim": "#C084FC",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#FFFFFF",
        "on-surface": "#FFFFFF",
        "tertiary-container": "#4C1D95",
        "primary-fixed": "#E9D5FF",
        "error-container": "#ffdad6",
        "surface-bright": "#0E153A",
        "secondary-container": "#1E1B4B",
        "on-secondary-fixed": "#FFFFFF",
        "on-tertiary-fixed-variant": "#C084FC",
        "secondary": "#7C3AED",
        "surface-container": "#0E1635",
        "on-error": "#ffffff",
        "surface-variant": "#121A3E",
        "surface-container-high": "#161F48",
        "tertiary": "#8B5CF6",
        "tertiary-fixed": "#D8B4FE",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "outline-variant": "#1E2952",
        "outline": "#2C3B75",
        "surface-container-highest": "#1C265A",
        "on-secondary-container": "#FFFFFF",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#C084FC",
        "primary-container": "#311099",
        "surface": "#0D132D",
        "surface-container-lowest": "#05081A",
        "on-primary-container": "#FFFFFF",
        "on-background": "#FFFFFF",
        "on-surface-variant": "#C5CBE9",
        "on-secondary": "#ffffff",
        "gold-accent": "#A66BFF"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "section-gap": "120px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-md": "16px"
      },
      "fontFamily": {
        "display": ["Cormorant Garamond", "Georgia", "serif"],
        "sans-premium": ["DM Sans", "Inter", "sans-serif"],
        "headline-md": ["PlusJakartaSans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["PlusJakartaSans", "sans-serif"],
        "headline-xl-mobile": ["PlusJakartaSans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["PlusJakartaSans", "sans-serif"],
        "display-lg-mobile": ["PlusJakartaSans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "display-hero": ["clamp(3rem, 8vw, 6rem)", { "lineHeight": "1.05", "letterSpacing": "-0.03em", "fontWeight": "300" }],
        "display-section": ["clamp(2.5rem, 5vw, 4.5rem)", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "label-premium": ["11px", { "lineHeight": "1", "letterSpacing": "0.25em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "display-lg-mobile": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
